[package]
name = "cobalt"
version = "0.1.0"
edition = "2021"

default-run = "main"

[[bin]]
name = "main"
path = "cbt.rs"
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
